### PR TITLE
[deps] bump `go-sev-guest` version to `v0.9.2`

### PR DESCRIPTION
**Pull request by msanft**
[v0.9.1](https://github.com/google/go-sev-guest/releases/tag/v0.9.1) of the `go-sev-guest` library included a fix that caused builds to fail due to a missing declaration on certain machines. This bumps the version to include this fix.

### CODE REVIEW

**Review by alexmwu — APPROVED** [review]
Is there a reason you didn't bump the main go-tpm-tools dependency? https://github.com/google/go-tpm-tools/blob/main/go.mod

**Comment by msanft** [comment]
> Is there a reason you didn't bump the main go-tpm-tools dependency? https://github.com/google/go-tpm-tools/blob/main/go.mod

Hey @alexmwu, thanks for the swift reply, and thanks for the heads-up! :smile:  I've `git add .` in the subdirectory, which caused the other files laying around in my local tree. I've added them now. If you could give the full changes one more quick look, I think we are good to merge.

**Comment by alexmwu** [comment]
Looks like there are failing tests @deeglaze can you take a look at this:
```
    verify_test.go:1125: VerifyAttestation(_, {[115 117 112 101 114 32 115 101 99 114 101 116 32 110 111 110 99 101] [0xc00019d9b0] false [] [] 0 0xc00019cd30}) = failed to verify memory encryption technology: VCEK cert product stepping number 01 is not 00, want "report field REPORT_DATA"
=== RUN   TestVerifyAttestationWithSevSnp/Bad_sev_root
    verify_test.go:1125: VerifyAttestation(_, {[115 117 112 101 114 32 115 101 99 114 101 116 32 110 111 110 99 101] [0xc00019d9b0] false [] [] 0 0xc00019cd40}) = failed to verify memory encryption technology: VCEK cert product stepping number 01 is not 00, want "error verifying VCEK certificate"
=== RUN   TestVerifyAttestationWithSevSnp/woops_all_debug
    verify_test.go:1125: VerifyAttestation(_, {[115 117 112 101 114 32 115 101 99 114 101 116 32 110 111 110 99 101] [0xc00019d9b0] false [] [] 0 0xc00019cd80}) = failed to verify memory encryption technology: VCEK cert product stepping number 01 is not 00, want "found unauthorized debug capability"
```

**Comment by msanft** [comment]
Obsolete due to #381

**Pull request closed without merging**
