### PR TITLE
Save binary SML at seal time.

### PR DESCRIPTION
**Pull request by Zabari**

### CODE REVIEW

**Comment by Zabari** [comment]
It seems that adding a new field to the proto requires a rebuild somewhere, is that something that needs to be done on my side, or somewhere in the build/testing process?

**Comment by jkl73** [comment]
> It seems that adding a new field to the proto requires a rebuild somewhere, is that something that needs to be done on my side, or somewhere in the build/testing process?

Try to run `go generate ./...` in the project dir

**Comment by jkl73** [comment]
Could you elaborate the use case for having the eventlog in the `SealedBytes`? Ideally the proto should contain just enough information for unseal.

An workaround can be calling `GetEventlog()` when you call `Seal()`, and save the eventlog in a separate file.

**Comment by josephlr** [comment]
> A workaround can be calling `GetEventlog()` when you call `Seal()`, and save the eventlog in a separate file.

I think I agree w/ @jkl73 here, given that the EventLog isn't used for Unsealing, it seems weird to include it in the Sealed Data proto, when a user can just include it own their own if they want.

**Pull request closed without merging**
