### PR TITLE
go.mod: Update dependencies and change CLI text output format

### PR DESCRIPTION
**Pull request by josephlr**
Signed-off-by: Joe Richey <joerichey@google.com>

### CODE REVIEW

**Comment by lulumel0n** [comment]
Per the CI lint error, we probably need to update the protobuf package to google.golang.org/protobuf/proto

**Comment by josephlr** [comment]
I'm currently working on updating all of the dependencies, including the protobuf knes

**Comment by ChriMarMe** [comment]
Divide and Conquer: #88

**Review by lulumel0n — APPROVED** [review]

**Comment by josephlr** [comment]
Two observable changes in this PR:

First, the `gotpm read pcr` command now doesn't use text proto formatting, so the output is more condensed (similar to `tpm2_pcrread`).

<details>
  <summary>Old PCR output</summary>
  
  ```
  ```
</details>
<details>
  <summary>New PCR output</summary>
  
  ```

  ```
</details>

Second, switching libraries slightly changes the output format for `gotpm seal`, but everything is still compatible (i.e. sealing/unsealing work between the old and new versions).

<details>
  <summary>Old Seal output</summary>
  
  ```
  priv: "\000 `)7R\215\217\2120\226\n\273c\354i\325\333\377h\361\010\326\212[Wr\3263\356\375T\\\370\000\020\254%\203\262\306\033H\016\261\377\247k\277n\366 \r\3205\177\014`\207R\310\177*;\323\350/\331\201P\343\206\0203\"\244h\336\r\366d\254\224\n,\177Ov\376\322\263\277\267\177\242\324\342\306\\\311"
pub: "\000\010\000\013\000\000\000R\000\000\000\020\000 \207%2?\263\313BOC\021\010\366\330i\020^\240\221\002\017T\022\313\0240\365\204\336\307\242\371y"
srk: RSA
certified_pcrs: <
  hash: SHA256
  pcrs: <
    key: 0
    value: "H\244-\354)l\245+\2739\361\004\025N.!\234n6w\266\321\034u\352\014#\207\276\346\337\317"
  >
  pcrs: <
    key: 1
    value: "\310[\"+\224\370\205\034\363\206\302A\035\352\026\021\316l\2429\013c:T\220\233\225\366\264\274wp"
  >
  pcrs: <
    key: 2
    value: "=E\214\376U\314\003\352\037D?\025b\276\354\215\365\034u\341J\237\317\232r4\241?\031\216yi"
  >
  pcrs: <
    key: 3
    value: "=E\214\376U\314\003\352\037D?\025b\276\354\215\365\034u\341J\237\317\232r4\241?\031\216yi"
  >
  pcrs: <
    key: 4
    value: "\014'-\303q&\245Gv\320T\267l\233oz\214\033\tB\003\310)#\270\324O5?\010\005Q"
  >
  pcrs: <
    key: 5
    value: "\201v;\330\361\261\301\214\375\274^\006\005\354\315\212\264\341\321[\302}\256a\350\265\237\274\205\036K\273"
  >
  pcrs: <
    key: 6
    value: "=E\214\376U\314\003\352\037D?\025b\276\354\215\365\034u\341J\237\317\232r4\241?\031\216yi"
  >
  pcrs: <
    key: 7
    value: "q4\304\241\211]\317\216\224\327\335A\222\234\226\3420\0074\2541~\333agB\304\215\275mk>"
  >
  pcrs: <
    key: 8
    value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  >
  pcrs: <
    key: 9
    value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  >
  pcrs: <
    key: 10
    value: "\014\301r0\021\352|5\024\362\361\233\213\211HL\346gz6,\335\316\365\2259\210\372C\230}X"
  >
  pcrs: <
    key: 11
    value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  >
  pcrs: <
    key: 12
    value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  >
  pcrs: <
    key: 13
    value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  >
  pcrs: <
    key: 14
    value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  >
  pcrs: <
    key: 15
    value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  >
  pcrs: <
    key: 16
    value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  >
  pcrs: <
    key: 17
    value: "\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377"
  >
  pcrs: <
    key: 18
    value: "\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377"
  >
  pcrs: <
    key: 19
    value: "\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377"
  >
  pcrs: <
    key: 20
    value: "\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377"
  >
  pcrs: <
    key: 21
    value: "\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377"
  >
  pcrs: <
    key: 22
    value: "\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377"
  >
  pcrs: <
    key: 23
    value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  >
>
creation_data: "\000\000\000\001\000\013\003\377\377\377\000 \202\312/\254y\034\213\225\014\036\375r\252\031\337\351\000?\352\316Er\007\307y\354\232\273\027T\364\307\001\000\013\000\"\000\013\314\201TH-\223\021X\312~Xm^\352\372\337\245\0301\343\023\344i\2633\325\233*[\255>\346\000\"\000\0136\372t\342!\210\205#E\003\333[\336X\322~\207\261\226\262\201]\014=\210\300\311y\255r\306(\000\000"
ticket: "\200!@\000\000\001\000 \267z\261\201\362\205`j\353\026\250A\247\367\n\013\213\226\305\360N\360\240\032\333(^\n\305?c~"
  ```
</details>
<details>
  <summary>New Seal output</summary>
  
  ```
  priv: "\x00 \xf4\x90f\u0785`\"\xb7{\xbe\x9eHP\xa54\xd8\xf6GP \xb1`\x03\xe3\xaf\xd3\xe1^\xdf\\\xa9\x1f\x00\x10\xe3\x14q(\x1f\xecZ\xb3\x87\xfb\xe7I>\xf9\xcanQ\xa9\xed\xb7\xa7\xd6\xe4l\tX\xd5e\xc0\xbfh\xf0\x85!tT\xa7l\x8c\xc6\xc9\x16\xb6i\x14\xe7\xfe\x9d-pG\x9e\xe3\xea0\xea\xf8e\x8b\\\x9dh\x03"
pub: "\x00\x08\x00\x0b\x00\x00\x00R\x00\x00\x00\x10\x00 \xb8\xf1\x1a\"K\x1e\x90\xd6/\xbbe\xf2\xbf\x1d\xb4\xb5\xaf\xc3\x13S}\x8c\xef\xc1u\xd9q\x05Ju\xb97"
srk: RSA
certified_pcrs: {
  hash: SHA256
  pcrs: {
    key: 0
    value: "H\xa4-\xec)l\xa5+\xbb9\xf1\x04\x15N.!\x9cn6w\xb6\xd1\x1cu\xea\x0c#\x87\xbe\xe6\xdf\xcf"
  }
  pcrs: {
    key: 1
    value: "\xc8[\"+\x94\xf8\x85\x1c\xf3\x86\xc2A\x1d\xea\x16\x11\xcel\xa29\x0bc:T\x90\x9b\x95\xf6\xb4\xbcwp"
  }
  pcrs: {
    key: 2
    value: "=E\x8c\xfeU\xcc\x03\xea\x1fD?\x15b\xbe\xec\x8d\xf5\x1cu\xe1J\x9f\u03dar4\xa1?\x19\x8eyi"
  }
  pcrs: {
    key: 3
    value: "=E\x8c\xfeU\xcc\x03\xea\x1fD?\x15b\xbe\xec\x8d\xf5\x1cu\xe1J\x9f\u03dar4\xa1?\x19\x8eyi"
  }
  pcrs: {
    key: 4
    value: "\x0c'-\xc3q&\xa5Gv\xd0T\xb7l\x9boz\x8c\x1b\tB\x03\xc8)#\xb8\xd4O5?\x08\x05Q"
  }
  pcrs: {
    key: 5
    value: "\x81v;\xd8\xf1\xb1\xc1\x8c\xfd\xbc^\x06\x05\xec\u034a\xb4\xe1\xd1[\xc2}\xaea\u8d5f\xbc\x85\x1eK\xbb"
  }
  pcrs: {
    key: 6
    value: "=E\x8c\xfeU\xcc\x03\xea\x1fD?\x15b\xbe\xec\x8d\xf5\x1cu\xe1J\x9f\u03dar4\xa1?\x19\x8eyi"
  }
  pcrs: {
    key: 7
    value: "q4\u0121\x89]\u03ce\x94\xd7\xddA\x92\x9c\x96\xe20\x074\xac1~\xdbagB\u010d\xbdmk>"
  }
  pcrs: {
    key: 8
    value: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
  }
  pcrs: {
    key: 9
    value: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
  }
  pcrs: {
    key: 10
    value: "\x0c\xc1r0\x11\xea|5\x14\xf2\U0005b2c9HL\xe6gz6,\xdd\xce\xf5\x959\x88\xfaC\x98}X"
  }
  pcrs: {
    key: 11
    value: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
  }
  pcrs: {
    key: 12
    value: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
  }
  pcrs: {
    key: 13
    value: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
  }
  pcrs: {
    key: 14
    value: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
  }
  pcrs: {
    key: 15
    value: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
  }
  pcrs: {
    key: 16
    value: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
  }
  pcrs: {
    key: 17
    value: "\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff"
  }
  pcrs: {
    key: 18
    value: "\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff"
  }
  pcrs: {
    key: 19
    value: "\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff"
  }
  pcrs: {
    key: 20
    value: "\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff"
  }
  pcrs: {
    key: 21
    value: "\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff"
  }
  pcrs: {
    key: 22
    value: "\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff"
  }
  pcrs: {
    key: 23
    value: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
  }
}
creation_data: "\x00\x00\x00\x01\x00\x0b\x03\xff\xff\xff\x00 \x82\xca/\xacy\x1c\x8b\x95\x0c\x1e\xfdr\xaa\x19\xdf\xe9\x00?\xea\xceEr\x07\xc7y\uc6bb\x17T\xf4\xc7\x01\x00\x0b\x00\"\x00\x0b\u0301TH-\x93\x11X\xca~Xm^\xea\xfa\u07e5\x181\xe3\x13\xe4i\xb33\u055b*[\xad>\xe6\x00\"\x00\x0b6\xfat\xe2!\x88\x85#E\x03\xdb[\xdeX\xd2~\x87\xb1\x96\xb2\x81]\x0c=\x88\xc0\xc9y\xadr\xc6(\x00\x00"
ticket: "\x80!@\x00\x00\x01\x00 H\x13K\xff\u00f1\xe00\xe1\xca;\xf0WM\xb4&)\x88\xdc^|@\xfc\xa2\xfb\x0e>\x80\xab1\u06d2"
  ```
</details>

**Comment by josephlr** [comment]
> Two observable changes in this PR:
> 
> First, the `gotpm read pcr` command now doesn't use text proto formatting, so the output is more condensed (similar to `tpm2_pcrread`).
> 
> Old PCR output
> New PCR output
> Second, switching libraries slightly changes the output format for `gotpm seal`, but everything is still compatible (i.e. sealing/unsealing work between the old and new versions).
> 
> Old Seal output
> New Seal output

**Pull request merged**
